# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a51e273d4f37907055c1d8a65aaa542084d3aad914f6ec604352b987a1e79073d76650cc30fab5671522511f2ff966f2dbc87e3cbf5e6ca5fc373392dcda6b4c

test:
  secret_key_base: 8f7dc4642e64df2f1ba243d1846d4331ad94bf633195200a2b81086ab39aa989a0b8b3cd551dd5788b0cc7d982d3a14af4c1ae6474c1ad4d52c3e48f4ca393c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
